accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('changepassword/', views.change_password, name='change_password'),
]

bookstore/urls.py
from django.urls import path
from . import views

app_name = 'bookstore'
urlpatterns = [
    path('', views.index, name='index'),
    path('api/', views.index_api),
    path('about/', views.about, name='about'),
    path('genre/<int:gn>/', views.genre, name='genre'),
    path('api/genre/<int:gn>/', views.genre_api),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

handler404='bookstore.views.page_not_found'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',include('bookstore.urls')),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, models.CASCADE)
    image = models.ImageField(upload_to='accounts', default='user.png')
    credit = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class SignUP(forms.Form):
    email = forms.EmailField(max_length=100, required=True)
    first_name = forms.CharField(min_length=3, max_length=20, required=True)
    password = forms.CharField(min_length=8, max_length=100, required=True)
    repeat_password = forms.CharField(max_length=100, required=True)

    def clean_email(self):
        if User.objects.filter(username=self.cleaned_data.get('email')).exists():
            raise ValidationError('User is exists')
        return self.cleaned_data.get('email')

    def clean_repeat_password(self):
        if self.cleaned_data.get('repeat_password') != self.cleaned_data.get('password'):
            raise ValidationError('Repate password is wrong!')
        return self.cleaned_data.get('repeat_password')


class Login(forms.Form):
    email = forms.EmailField(max_length=100, required=True)
    password = forms.CharField(min_length=8, max_length=100, required=True)


class Profile(forms.Form):
    image = forms.ImageField(required=False)
    first_name = forms.CharField(min_length=3, max_length=20, required=True)

    def clean_image(self):
        if self.cleaned_data.get('image'):
            if self.cleaned_data.get('image').size > 5242880:
                raise ValidationError('Maximum size image is 5MB')
        return self.cleaned_data['image']


class Change_password(forms.Form):
    old_password = forms.CharField(max_length=100, required=True)
    new_password = forms.CharField(min_length=8, max_length=100, required=True)
    repeat_password = forms.CharField(max_length=100, required=True)

    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def clean_old_password(self):
        if not self._user.check_password(self.cleaned_data.get('old_password')):
            raise ValidationError('Old password is wrong')
        return self.cleaned_data['old_password']

    def clean_repeat_password(self):
        if self.cleaned_data.get('repeat_password') != self.cleaned_data.get('new_password'):
            raise ValidationError('Repeat password is wrong')

accounts/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from . import forms, models


def signup(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = forms.SignUP(request.POST)
            if form.is_valid():
                user = User.objects.create_user(form.cleaned_data['email'], password=form.cleaned_data['password'],
                                                first_name=form.cleaned_data['first_name'])
                models.Profile.objects.create(user=user)
                return render(request, 'accounts/user.html')
        else:
            form = forms.SignUP()
        context = {'form': form}
        return render(request, 'accounts/signup.html', context=context)
    else:
        return HttpResponseRedirect(reverse('bookstore:index'))


def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        return HttpResponseRedirect(reverse('accounts:login'))
    return HttpResponseRedirect(reverse('bookstore:index'))


def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = forms.Login(request.POST)
            if form.is_valid():
                user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password'])
                if user:
                    context = {'form': form, 'user': user}
                    login(request, user=user)
                    if request.GET.get('next'):
                        return HttpResponseRedirect(request.GET['next'])
                    return render(request, 'accounts/succeed_login.html', context=context)
                else:
                    context = {'form': form, 'error': 'email or password is wrong'}
            else:
                context = {'form': form}
        else:
            form = forms.Login()
            context = {'form': form}
        return render(request, 'accounts/login.html', context=context)
    else:
        return HttpResponseRedirect(reverse('bookstore:index'))


@login_required
def profile(request):
    context = {'user': request.user}
    if request.method == 'POST':
        form = forms.Profile(request.POST, request.FILES)
        if form.is_valid():
            if request.user.first_name != form.cleaned_data['first_name']:
                context['update'] = True
                request.user.first_name = form.cleaned_data['first_name']
                request.user.save()
            if form.cleaned_data.get('image'):
                context['update'] = True
                request.user.profile.image = form.cleaned_data['image']
                request.user.profile.save()
    else:
        form = forms.Profile()
    context['form'] = form
    return render(request, 'accounts/profile.html', context=context)


@login_required()
def change_password(request):
    context = {'update': False}
    if request.method == 'POST':
        form = forms.Change_password(request.POST, user=request.user)
        if form.is_valid():
            context['update'] = True
            request.user.set_password(form.cleaned_data['new_password'])
            request.user.save()
            return render(request,'accounts/succeed_change_password.html')
    else:
        form = forms.Change_password(user=request.user)
    context['form'] = form
    return render(request, 'accounts/change_password.html',context=context)

templates/accounts/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
    <link href="{% static "accounts/css/bootstrap.min.css" %}" rel="stylesheet">
</head>
<body>
<div class="container-lg d-grid gap-2 d-md-flex justify-content-md-center" style="margin-top: 1rem">
    <form method="POST">{% csrf_token %}
        <div class="mb-3">
            <label class="form-label" style="font-size: 1rem;font-weight: 300">Old password</label>
            <input type="password" class="form-control" name="old_password" maxlength="100" style="font-size: 1rem;font-weight: 300">
            {% if form.old_password.errors %}
                <div class="alert alert-warning" style="margin: 5px auto;font-size: 1rem;font-weight: 300">
                    {{ form.old_password.errors }}
                </div>
            {% endif %}
        </div>
        <div class="mb-3">
            <label class="form-label" style="font-size: 1rem;font-weight: 300">New password</label>
            <input type="password" class="form-control" name="new_password" maxlength="100" style="margin: 0 auto;font-size: 1rem;font-weight: 300">
            {% if form.new_password.errors %}
                <div class="alert alert-warning" style="margin: 5px auto;font-size: 1rem;font-weight: 300">
                    {{ form.new_password.errors }}
                </div>
            {% endif %}
        </div>
        <div class="mb-3">
            <label class="form-label" style="font-size: 1rem;font-weight: 300">Repeat password</label>
            <input type="password" class="form-control" name="repeat_password" maxlength="100" style="margin: 0 auto;font-size: 1rem;font-weight: 300">
            {% if form.repeat_password.errors %}
                <div class="alert alert-warning" style="margin: 5px auto;font-size: 1rem;font-weight: 300">
                    {{ form.repeat_password.errors }}
                </div>
            {% endif %}
        </div>
        <div class="d-grid gap-2 d-md-flex justify-content-center">
            <button class="btn btn-primary" type="submit">Update</button>
            <a class="btn btn-secondary " href="{% url "accounts:profile" %}">Back</a>
        </div>
        {% if update %}
            <div class="alert alert-success" style="margin: 5px auto;font-size: 1rem;font-weight: 300">
                    Password updated
            </div>
        {% endif %}
    </form>
</div>
</body>
</html>

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static "accounts/images/icons/favicon.ico" %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/bootstrap/css/bootstrap.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static "accounts/fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static "accounts/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/animate/animate.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/css-hamburgers/hamburgers.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/animsition/css/animsition.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/select2/select2.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/daterangepicker/daterangepicker.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/css/util.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "accounts/css/main.css" %}">
    <!--===============================================================================================-->
</head>
<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
            <form class="login100-form validate-form flex-sb flex-w" method="POST">{% csrf_token %}
                <span class="login100-form-title p-b-32">
						Account Login
					</span>

                <span class="txt1 p-b-11">
						Email
					</span>
                <div class="wrap-input100 validate-input m-b-36" data-validate="Email is required">
                    <input class="input100" type="text" name="email">
                    <span class="focus-input100"></span>
                    {% if form.email.errors %}
                        <div class="alert-warning" role="alert">
                            {{ form.email.errors }}
                        </div>
                    {% endif %}
                </div>

                <span class="txt1 p-b-11">
						Password
					</span>
                <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
                    <input class="input100" type="password" name="password">
                    <span class="focus-input100"></span>
                    {% if form.password.errors %}
                        <div class="alert-warning" role="alert">
                            {{ form.password.errors }}
                        </div>
                    {% endif %}
                </div>
                {% if error %}
                    <div class="alert alert-warning" role="alert">
                        {{ error }}
                    </div>
                {% endif %}
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn">
                        Login
                    </button>
                </div>

            </form>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
<script src="{% static "accounts/vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/vendor/animsition/js/animsition.min.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/vendor/bootstrap/js/popper.js" %}"></script>
<script src="{% static "accounts/vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/vendor/select2/select2.min.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/vendor/daterangepicker/moment.min.js" %}"></script>
<script src="{% static "accounts/vendor/daterangepicker/daterangepicker.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/vendor/countdowntime/countdowntime.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/js/main.js" %}"></script>

</body>
</html>

templates/accounts/profile.html
{% load static %}
{% get_media_prefix as media %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link href="{% static "accounts/css/bootstrap.min.css" %}" rel="stylesheet">
</head>
<body>
<div class="container-lg d-grid gap-2 d-md-flex justify-content-md-center">
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="mb-3">
            <img src="{{ media }}{{ user.profile.image }}" alt="profile" style="border-radius: 50%;border: 0.01px solid;width: 10rem;height: 10rem;margin: 10px"/>
            <input type="file" class="form-control" name="image" style="font-size: 1rem;font-weight: 300">
            {% if form.image.errors %}
                <div class="alert alert-warning" style="margin: 5px auto;font-size: 1rem;font-weight: 300">
                    {{ form.image.errors }}
                </div>
            {% endif %}
        </div>
        <div class="mb-3">
            <label class="form-label" style="font-size: 1rem;font-weight: 300">Firstname</label>
            <input type="text" class="form-control" name="first_name" maxlength="20" value="{{ user.first_name }}" style="margin: 0 auto;font-size: 1rem;font-weight: 300">
            {% if form.first_name.errors %}
                <div class="alert alert-warning" style="margin: 5px auto;font-size: 1rem;font-weight: 300">
                    {{ form.first_name.errors }}
                </div>
            {% endif %}
        </div>
        <div class="d-grid gap-2 d-md-flex justify-content-center">
            <button class="btn btn-primary" type="submit">Update</button>
            <a class="btn btn-secondary " href="{% url "accounts:change_password" %}">ChangePassword</a>
        </div>
        {% if update %}
            <div class="alert alert-success" style="margin: 5px auto;font-size: 1rem;font-weight: 300">
                    Profile updated
            </div>
        {% endif %}
    </form>
</div>
</body>
</html>

templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SignUp</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static "accounts/images/icons/favicon.ico" %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/bootstrap/css/bootstrap.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static "accounts/fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/animate/animate.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/css-hamburgers/hamburgers.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/animsition/css/animsition.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/select2/select2.min.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/vendor/daterangepicker/daterangepicker.css" %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "accounts/css/util.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "accounts/css/main.css" %}">
    <!--===============================================================================================-->
</head>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
            <form class="login100-form validate-form flex-sb flex-w" method="POST">{% csrf_token %}
					<span class="login100-form-title p-b-32">
						Account SignUp
					</span>

                <span class="txt1 p-b-11">
						Email
					</span>
                <div class="wrap-input100 validate-input m-b-36" data-validate="Email is required">
                    <input class="input100" type="text" name="email">
                    <span class="focus-input100"></span>
                    {% if form.email.errors %}
                        <div class="alert-warning" role="alert">
                            {{ form.email.errors }}
                        </div>
                    {% endif %}
                </div>
                <span class="txt1 p-b-11">
						FirstName
					</span>
                <div class="wrap-input100 validate-input m-b-36" data-validate="FirstName is required">
                    <input class="input100" maxlength="20" type="text" name="first_name">
                    <span class="focus-input100"></span>
                    {% if form.first_name.errors %}
                        <div class="alert-warning" role="alert">
                            {{ form.first_name.errors }}
                        </div>
                    {% endif %}
                </div>

                <span class="txt1 p-b-11">
						Password
					</span>
                <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
                    <input class="input100" type="password" name="password">
                    <span class="focus-input100"></span>
                    {% if form.password.errors %}
                        <div class="alert-warning" role="alert">
                            {{ form.password.errors }}
                        </div>
                    {% endif %}
                </div>
                <span class="txt1 p-b-11">
						Repeat password
					</span>
                <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
                    <input class="input100" type="password" name="repeat_password">
                    <span class="focus-input100"></span>
                    {% if form.repeat_password.errors %}
                        <div class="alert-warning" role="alert">
                            {{ form.repeat_password.errors }}
                        </div>
                    {% endif %}
                </div>


                <div class="container-login100-form-btn">
                    <button class="login100-form-btn">
                        SignUp
                    </button>
                </div>

            </form>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
<script src="{% static "accounts/vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/vendor/animsition/js/animsition.min.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/vendor/bootstrap/js/popper.js" %}"></script>
<script src="{% static "accounts/vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/vendor/select2/select2.min.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/vendor/daterangepicker/moment.min.js" %}"></script>
<script src="{% static "accounts/vendor/daterangepicker/daterangepicker.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/vendor/countdowntime/countdowntime.js" %}"></script>
<!--===============================================================================================-->
<script src="{% static "accounts/js/main.js" %}"></script>

</body>
</html>

templates/accounts/succeed_change_password.html
{% extends "accounts/succeed_login.html" %}
{% block title %}Change password{% endblock %}
{% block heading %}Password changed successfully{% endblock %}
{% block content %}
    Please login again,waiting for redirect to login page...
{% endblock %}

templates/accounts/succeed_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Login{% endblock %}</title>
    <link href="{% static "accounts/css/bootstrap.min.css" %}" rel="stylesheet">
</head>
<body>
<h1>{% block heading %}Succeed login{% endblock %}</h1>
<p class="lead" style="font-size: 30px">{% block content %}Waiting for redirect {% endblock %}<a href="{% url "accounts:login" %}">HERE</a></p>
<div class="spinner-border" role="status">
    <span class="visually-hidden">Loading...</span>
</div>
<script>window.setTimeout(function () {

    // Move to a new location or you can do something else
    window.location.href = "{% url "bookstore:index" %}";

}, 3000);</script>
</body>
</html>

templates/accounts/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
</head>
<body>
<h1>User created</h1>
<p class="lead" style="font-size: 30px">
    Login to your account from <a href="{% url "accounts:login" %}">HERE</a>
</p>
</body>
</html>