accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('changepassword/', views.change_password, name='change_password'),
]

bookstore/urls.py
from django.urls import path
from . import views

app_name = 'bookstore'
urlpatterns = [
    path('', views.index, name='index'),
    path('api/', views.index_api),
    path('about/', views.about, name='about'),
    path('genre/<int:gn>/', views.genre, name='genre'),
    path('api/genre/<int:gn>/', views.genre_api),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

handler404='bookstore.views.page_not_found'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',include('bookstore.urls')),
]

bookstore/models.py
from django.contrib.auth.models import User
from django.db import models


class Book(models.Model):
    book = models.CharField(max_length=100)
    description = models.TextField(max_length=300)
    LOVER, FANTASTY, SCIENCE_FICTION, ADVENTURE, PANIC, HISTORICAL = 1, 2, 3, 4, 5, 6
    choice_genre = (
        (LOVER, 'Lover'),
        (FANTASTY, 'Fantasy'),
        (SCIENCE_FICTION, 'Science Fiction'),
        (ADVENTURE, 'Adventure'),
        (PANIC, 'Panic'),
        (HISTORICAL, 'Historical')
    )
    genre = models.IntegerField(choices=choice_genre)
    price = models.IntegerField(default=0)
    count_book = models.IntegerField(default=0)
    image = models.ImageField(upload_to='books', default='book.jpeg')

    def __str__(self):
        return self.book


class Buy(models.Model):
    """
        Generate unique tokens for each purchase
    """
    token = models.CharField(max_length=100, primary_key=True)
    user = models.ForeignKey(User, models.CASCADE)
    book = models.ForeignKey(Book, models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.token

bookstore/views.py
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import render
from django.core.paginator import Paginator
from . import models


def index(request):
    context = {'genres': models.Book.choice_genre}
    if request.GET.get('p'):
        page = request.GET['p']
    else:
        page = 1
    context['query'] = request.GET.get('q')
    if context['query']:
        book_list = models.Book.objects.filter(book__contains=request.GET['q'])
        if book_list.exists():
            paginator = Paginator(book_list, 9)
            books = paginator.get_page(page)
            context['books'] = books
            context['query'] = request.GET['q']
    return render(request, 'bookstore/index.html', context=context)


def index_api(request):
    if request.GET.get('p'):
        page = request.GET['p']
    else:
        page = 1
    if request.GET.get('q'):
        book_list = models.Book.objects.filter(book__contains=request.GET['q'])
        if book_list.exists():
            paginator = Paginator(book_list, 9)
            books = paginator.get_page(page)
            data = {
                'ok': True,
                'page': page,
                'total_pages': books.paginator.num_pages,
                'results': [{'name': book.book,
                             'genre': book.get_genre_display(),
                             'description': book.description,
                             'price': book.price,
                             'image': settings.MEDIA_URL+book.image.name
                             } for book in books]
            }
            return JsonResponse(data)
    return JsonResponse({'ok': False, 'result': 'no parameter'})


def about(request):
    return render(request, 'bookstore/about.html',context={'genres': models.Book.choice_genre})


def genre(request, gn):
    context = {'books': None, 'genres': models.Book.choice_genre}
    book_list = models.Book.objects.filter(genre=gn)
    if request.GET.get('p'):
        page = request.GET['p']
    else:
        page = 1
    if book_list.exists():
        paginator = Paginator(book_list, 9)
        books = paginator.get_page(page)
        context['books'] = books
    return render(request, 'bookstore/gener.html', context=context)

def genre_api(request, gn):
    book_list = models.Book.objects.filter(genre=gn)
    if request.GET.get('p'):
        page = request.GET['p']
    else:
        page = 1
    if book_list.exists():
        paginator = Paginator(book_list, 9)
        books = paginator.get_page(page)
        data = {
            'ok': True,
            'page': page,
            'total_pages': books.paginator.num_pages,
            'results': [{'name': book.book,
                         'genre': book.get_genre_display(),
                         'description': book.description,
                         'price': book.price,
                         'image': settings.MEDIA_URL + book.image.name
                         } for book in books]
        }
        return JsonResponse(data)

def page_not_found(request, exception):
    return render(request, '404.html')

templates/bookstore/about.html
{% extends 'bookstore/index.html' %}
{% block title %}About{% endblock %}
{% block body %}<p class="lead" style="margin: 3rem 35%; font-size: 50px">Bookstore App</p> {% endblock %}

templates/bookstore/gener.html
{% extends "bookstore/index.html" %}
{% block title %}Genre{% endblock %}
{% block body %}
    {% if books %}
        <div style="margin: 4rem auto;width: 35%">
            <p class="lead" style="font-size: 40px">
                Results
            </p>
        </div>
        <div class="album py-5 bg-light">
            <div class="container-lg">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-3">
                    {% for book in books %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <img class="bd-placeholder-img card-img-top" width="100%" height="225" role="img"
                                     src="{{ media }}{{ book.image }}" preserveAspectRatio="xMidYMid slice"
                                     focusable="false"/>
                                <div class="card-body">
                                    <h3>{{ book.book }}</h3>
                                    <h5><span class="badge bg-success">{{ book.get_genre_display }}</span></h5>
                                    <p class="card-text lead">{{ book.description }}</p>
                                    <h4 align="center"><span class="badge bg-dark">$ {{ book.price }}</span></h4>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <h5 align="center"><span
                class="badge bg-secondary">Page {{ books.number }} of {{ books.paginator.num_pages }}</span></h5>
        <div align="center">
            <div class="btn-group btn-group-lg" role="group">
                {% if books.has_next and books.has_previous %}
                    <a type="button" href="?p={{ books.previous_page_number }}"
                       class="btn btn-primary">≪</a>
                    <a type="button" href="?p={{ books.next_page_number }}" class="btn btn-primary">≫</a>
                {% elif books.has_previous %}
                    <a type="button" href="?p={{ books.previous_page_number }}"
                       class="btn btn-primary">≪</a>
                {% elif books.has_next %}
                    <a type="button" href="?p={{ books.next_page_number }}" class="btn btn-primary">≫</a>
                {% endif %}
            </div>
        </div>
    {% else %}
        <div style="margin: 4rem auto;width: 35%">
            <p class="lead" style="font-size: 40px">
                No result
            </p>
        </div>
    {% endif %}
{% endblock %}

templates/bookstore/index.html
{% load static %}
{% get_media_prefix as media %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Bookstore{% endblock %}</title>
    <link href="{% static "bookstore/css/bootstrap.min.css" %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <span class="navbar-brand">Bookstore</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02"
                aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url "bookstore:index" %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url "bookstore:about" %}">About</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Geners
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {%  for val,item in genres%}
                            <li><a class="dropdown-item" href="{% url "bookstore:genre" gn=val %}">{{ item }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <form class="d-flex" method="GET">
                    <input class="form-control me-2 form-control-sm" type="search" name="q" placeholder="Search" aria-label="Search">
                    <button class="btn btn-sm btn-outline-success" type="submit">Search</button>
                </form>
                {% if user.is_authenticated %}
                    <div class="dropdown">
                        <button class="btn btn-sm btn-success dropdown-toggle me-2" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.first_name }}
                        </button>
                        <img src="{{ media }}{{ user.profile.image }}" alt="profile" style="border-radius: 50%;width: 2.5rem;height: 2.5rem"/>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a class="dropdown-item" href="{% url "accounts:profile" %}">Profile</a></li>
                            <li><a class="dropdown-item disabled" href="#">credit : ${{ user.profile.credit }}</a></li>
                            <li><a class="dropdown-item" href="{% url "accounts:logout" %}">Logout</a></li>
                        </ul>
                    </div>
                {% else %}
                    <a class="btn btn-sm btn-primary" href="{% url "accounts:login" %}">Login</a>
                    <a class="btn btn-sm btn-primary" href="{% url "accounts:signup" %}">SignUp</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{{ media }}bookstore1.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="{{ media }}bookstore2.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="{{ media }}bookstore3.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
{% block body %}
    {% if books %}
        <div style="margin: 4rem auto;width: 35%">
            <p class="lead" style="font-size: 40px">
                Results
            </p>
        </div>
        <div class="album py-5 bg-light">
            <div class="container-lg">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-3">
                    {% for book in books %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <img class="bd-placeholder-img card-img-top" width="100%" height="225" role="img" src ="{{ media }}{{ book.image }}" preserveAspectRatio="xMidYMid slice" focusable="false"/>
                                <div class="card-body">
                                    <h3>{{ book.book }}</h3>
                                    <h5><span class="badge bg-success">{{ book.get_genre_display }}</span></h5>
                                    <p class="card-text lead">{{ book.description }}</p>
                                    <h4 align="center"><span class="badge bg-dark">$ {{ book.price }}</span></h4>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <h5 align="center"><span class="badge bg-secondary">Page {{ books.number }} of {{ books.paginator.num_pages }}</span></h5>
        <div align="center">
            <div class="btn-group btn-group-lg" role="group">
                {% if books.has_next and books.has_previous %}
                    <a type="button" href="?q={{ query }}&p={{ books.previous_page_number }}"
                       class="btn btn-primary">≪</a>
                    <a type="button" href="?q={{ query }}&p={{ books.next_page_number }}" class="btn btn-primary">≫</a>
                {% elif books.has_previous %}
                    <a type="button" href="?q={{ query }}&p={{ books.previous_page_number }}"
                       class="btn btn-primary">≪</a>
                {% elif books.has_next %}
                    <a type="button" href="?q={{ query }}&p={{ books.next_page_number }}" class="btn btn-primary">≫</a>
                {% endif %}
            </div>
        </div>
    {% elif query != None %}
        <div style="margin: 4rem auto;width: 35%">
            <p class="lead" style="font-size: 40px">
                No result
            </p>
        </div>
    {% else %}
        <div style="margin: 4rem auto;width: 35%">
            <p class="lead" style="font-size: 40px">
                Welcome
            </p>
        </div>
    {% endif %}
{% endblock %}
<script src="{% static "bookstore/js/bootstrap.bundle.min.js" %}"></script>
</body>
</html>